import { Clock3, MessageSquareText, Pencil, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Conversation, UserSettings } from '../../types'

type Props = { conversations: Conversation[]; settings: UserSettings; onOpen: (id: string) => void; onDelete: (id: string) => void; onRename: (id: string, title: string) => void }

export default function HistoryPage({ conversations, settings, onOpen, onDelete, onRename }: Props) {
  const [search, setSearch] = useState('')
  const filtered = useMemo(() => conversations.filter((item) => `${item.title} ${item.messages.map((message) => message.content).join(' ')}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).sort((a, b) => b.updatedAt - a.updatedAt), [conversations, search])
  const format = (timestamp: number) => settings.dateFormat === 'YYYY-MM-DD' ? new Date(timestamp).toISOString().slice(0, 10) : new Date(timestamp).toLocaleDateString('pt-BR')
  return <main className="workspace page-workspace"><header className="workspace-header"><div className="header-title"><strong>Histórico</strong><span>{conversations.length} {conversations.length === 1 ? 'conversa salva' : 'conversas salvas'} neste navegador</span></div></header><section className="content-page"><div className="page-heading"><div><p className="section-kicker">CONVERSAS</p><h1>Seu histórico</h1></div><label className="page-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar no histórico" /></label></div><div className="list-panel">{filtered.map((conversation) => <article className="conversation-list-item" key={conversation.id}><button className="conversation-open" onClick={() => onOpen(conversation.id)}><span className="list-icon"><MessageSquareText size={17} /></span><span><strong>{conversation.title}</strong><small>{conversation.messages.length} mensagens · Atualizada em {format(conversation.updatedAt)}</small></span></button><div className="row-actions"><button onClick={() => { const title = window.prompt('Novo título', conversation.title); if (title?.trim()) onRename(conversation.id, title.trim()) }} aria-label="Renomear"><Pencil size={15} /></button><button onClick={() => onDelete(conversation.id)} aria-label="Excluir"><Trash2 size={15} /></button></div></article>)}{!filtered.length && <div className="page-empty"><Clock3 size={24} /><strong>Nenhuma conversa encontrada</strong><span>Tente buscar por outro termo.</span></div>}</div></section></main>
}
